Repository opensistemas-hub/osbrain, pull requests merged in 2018-04, with the labels that each got.

#285 Spelling revision
  docs/source/about.rst
  docs/source/advanced_proxy_handling.rst
  docs/source/considerations.rst
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/timers.rst
  docs/source/transport_protocol.rst
  examples/explicit_serialization.py
  osbrain/agent.py
  osbrain/common.py
  osbrain/helper.py
  osbrain/nameserver.py
  osbrain/tests/test_agent.py
  osbrain/tests/test_agent_async_requests_handlers.py
  osbrain/tests/test_agent_pubsub_topics.py
  osbrain/tests/test_agent_sync_publications_handlers.py
  osbrain/tests/test_bugs.py
  osbrain/tests/test_proxy.py
Labels: enhancement

#289 Test nameserver shutdown with a ConnectionClosedError
  osbrain/tests/test_proxy.py
Labels: test

#295 Check no print statements left in source code
  setup.py
  tox.ini
Labels: enhancement, test

#296 Fix agent inheritance test to wait for running
  osbrain/tests/test_agent.py
Labels: bug, test

#297 Fix AppVeyor badge image in README file
  README.rst
Labels: enhancement

#298 Fixed code example typo - renamed param name 'handlers' to 'handler'
  examples/pub_sub_more_on_filter.py
Labels: bug
